### ISSUE TITLE
Invalid address format

### ISSUE THREAD

**Issue by noroot** [cadrspace/endpoint-scripts#1]
Fix invalid address format, - number of aud. must be at the end of address string
https://www.dropbox.com/s/cjwxihr56p91m94/Screenshot%202015-07-10%2016.36.10.png?dl=0

**Comment by noroot** [comment]
See screenshot
![screenshot 2015-07-10 16 36 10](https://cloud.githubusercontent.com/assets/59066/8619853/27593410-2723-11e5-9fb6-5d3610876bc1.png)

Address string should be "Nizhniy Novgorod, Russian Federation,  Studentcheskaya st. 6, aud. 054"

**Comment by artyom-poptsov** [comment]
Fixed in 272b266.  Please check if it works for you.

**Comment by noroot** [comment]
Checked, it works.
